### PR TITLE
feat :sparkles:: Load and save models functions

### PR DESCRIPTION
**Pull request by elsheikh21**
I opened this PR as per our [Issue #24 ](https://github.com/xuhongzuo/DeepOD/issues/24), to load and save models

I followed the same conventions as much as possible, please feel free to edit the repo or shoot me a comment

Thanks and have a great day @xuhongzuo

### CODE REVIEW

**Comment by xuhongzuo** [comment]
Hi @elsheikh21 ,
Thanks so much for your interest, and I apologize for my late reply.  

I reviewed your commits. It is a little weird to implement load_model as an inner-class function. 

Suppose that the class of a detection model is instantiated as a variable `model1`, and has been trained and saved. 
If we want to use this saved model, then we should instantiate a new variable `model2`, and use `load_model`, but this function does not return the saved model to this variable `model2`, but produces a new instantiated variable `model3`. Of course, we can directly return this new variable to replace the `model2`. 

```
model1 = Class()
model1.fit(X)
model1.save_model(path)

model2 = Class()
model3 = model2.load_model(path)
```

This implementation is totally right, but personally, it might be not very elegant.

**Comment by elsheikh21** [comment]
@xuhongzuo 
thanks and no need to apologize. 
Anyway, I totally understand your point and I do agree with you, 

I could not implement it only inside the class `DeepSVDD`, as I also require the functionality from all other models. So, It was not very practical to rewrite the same method in all classes, that's why I went to `BaseClassAD`

```{python}
# An example of the Implementation of the Save and Load Model inside children's classes
Class DeepSVDD(BaseClassAD):
      # Existing code
      def save_model(se;f, path):
            with open(f"{path}.pkl", mode="wb") as f:
                  pickle.dump(self, f)
      
      def load_model(self, path):
            model = None
            with open(f"{path}.pkl", mode="rb") as f:
                     model = pickle.load(f)
             return model
``` 

I tried changing the `load_method(self, path)` instead of doing `self = pickle.load(f)` as follows, but it did not work obviously, I failed to point out the problem source,

```
# An Example of implementation of the same functionality inside the Parent Class
Class BaseClassAD(BaseClassAD):
      # Existing code
      def save_model(se;f, path):
            with open(f"{path}.pkl", mode="wb") as f:
                  pickle.dump(self, f)
      
      def load_model(self, path):
            with open(f"{path}.pkl", mode="rb") as f:
                     self = pickle.load(f)
```

So the solution provided was mainly focused on functionality and not code elegancy, but let me know how to approach the problem so we have an elegant functional code

Thanks again and regards

**Comment by elsheikh21** [comment]
After searching a simple obvious idea came to mind which is adding the `load_model()` as a class method of `BaseDeepAD` in this case, we can load the model easily


```
class BaseDeepAD:
# Existing code
     @classmethod
     def load_model(cls, path):
         with open(f"{path}.pkl", mode="rb") as f:
             return pickle.load(f)
```


so now it is tested locally and functions as following 

```
model1 = DeepSVDD() # or any other child model (of BaseDeepAD)
model1.fit(X)
model1.save_model(path)

model2 = DeepSVDD.load_model(path)
```


Please let me know wdyt?

**Comment by xuhongzuo** [comment]
I just tried this solution. It seems very fantastic.

**Pull request merged**
