### PR TITLE
add TcnEDBlock in base_networks.py and add tcn_utils.py

### PR DESCRIPTION
**Pull request by real-lhj**
1. 在base_networks.py里添加了TcnEDBlock。
2. 在core目录下添加了tcn_utils.py，其中有两个类TemporalBlock和TemporalBlockTranspose，分别被TcnEDBlock的encoder和decoder调用。

### CODE REVIEW

**Comment by xuhongzuo** [comment]
Hi HJ,

Thanks for the Pull Request on a new network structure for time-series sequential data. 

Since most current deep models rely on representation learning rather than the auto-encoder structure. 
Could you please also add a TCN network structure (output the representation where the dimension is determined by a parameter named `n_output`, like MLP in `base_network.py`) by removing the reconstruction stage? 

Also, I noticed that this PR does not pass the testing, it might be because of the importation of the `tcn_utils` module. 
use `from deepod.core.tcn_utils import TemporalBlock, TemporalBlockTranspose` to replace
`from tcn_utils import TemporalBlock, TemporalBlockTranspose`.

Cheers!

**Comment by xuhongzuo** [comment]
Hi HJ,

Thanks for the Pull Request on a new network structure for time-series sequential data. 

Since most current deep models rely on representation learning rather than the auto-encoder structure. 
Could you please also add a TCN network structure (output the representation where the dimension is determined by a parameter named `n_output`, like MLP in `base_network.py`) by removing the reconstruction stage? 

Also, I noticed that this PR does not pass the testing, it might be because of the importation of the `tcn_utils` module. 
use `from deepod.core.tcn_utils import TemporalBlock, TemporalBlockTranspose` to replace
`from tcn_utils import TemporalBlock, TemporalBlockTranspose`.

Cheers!

**Comment by xuhongzuo** [comment]
BTW, could you also replace the Chinese commends with English?

**Comment by real-lhj** [comment]
Okay, I understand. I will change the auto-encoder structure to a representation learning network, and also fix some bugs. Thanks for your suggestions!😊

**Comment by real-lhj** [comment]
Okay, I understand. I will change the auto-encoder structure to a representation learning network, and also fix some bugs. Thanks for your suggestions!😊

**Pull request closed without merging**
